{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jmailen.gradle",
    "module": "kotlinter-gradle",
    "version": "3.12.0-local",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinter-gradle-3.12.0-local.jar",
          "url": "kotlinter-gradle-3.12.0-local.jar",
          "size": 127324,
          "sha512": "6d4995675e3c168479cdb2e2e682c29bcfa0485ee20aa631e36f73e307ed3865f69f5a5418b26198e9d75c72edf448c5b89d0be67fc003bfc8e404a8bdd7f4d1",
          "sha256": "cbf6b3a328ed663c8392507dbba27373589d34c1d5a46f821ba94113c6e6c8a9",
          "sha1": "97bbe8ca9eb331f3c7952c44f9a771811b31c0f9",
          "md5": "8469c021b30d98a2a17d52118659c025"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.pinterest.ktlint",
          "module": "ktlint-core",
          "version": {
            "requires": "0.47.1"
          }
        },
        {
          "group": "com.pinterest.ktlint",
          "module": "ktlint-reporter-checkstyle",
          "version": {
            "requires": "0.47.1"
          }
        },
        {
          "group": "com.pinterest.ktlint",
          "module": "ktlint-reporter-json",
          "version": {
            "requires": "0.47.1"
          }
        },
        {
          "group": "com.pinterest.ktlint",
          "module": "ktlint-reporter-html",
          "version": {
            "requires": "0.47.1"
          }
        },
        {
          "group": "com.pinterest.ktlint",
          "module": "ktlint-reporter-plain",
          "version": {
            "requires": "0.47.1"
          }
        },
        {
          "group": "com.pinterest.ktlint",
          "module": "ktlint-reporter-sarif",
          "version": {
            "requires": "0.47.1"
          }
        },
        {
          "group": "com.pinterest.ktlint",
          "module": "ktlint-ruleset-experimental",
          "version": {
            "requires": "0.47.1"
          }
        },
        {
          "group": "com.pinterest.ktlint",
          "module": "ktlint-ruleset-standard",
          "version": {
            "requires": "0.47.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinter-gradle-3.12.0-local.jar",
          "url": "kotlinter-gradle-3.12.0-local.jar",
          "size": 127324,
          "sha512": "6d4995675e3c168479cdb2e2e682c29bcfa0485ee20aa631e36f73e307ed3865f69f5a5418b26198e9d75c72edf448c5b89d0be67fc003bfc8e404a8bdd7f4d1",
          "sha256": "cbf6b3a328ed663c8392507dbba27373589d34c1d5a46f821ba94113c6e6c8a9",
          "sha1": "97bbe8ca9eb331f3c7952c44f9a771811b31c0f9",
          "md5": "8469c021b30d98a2a17d52118659c025"
        }
      ]
    }
  ]
}
